version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "23093:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: inpc_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "24093:5432"
