# Generated by Django 5.1.4 on 2025-01-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_productprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='point_of_sale',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='value',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='type',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cart'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='pointdevente',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=252),
        ),
    ]
